import { StyleSheet } from "react-native";
import { COLORS } from "../vars";

export const Alert = StyleSheet.create({
  error: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    height: 64,
    maxHeight: 64,
    width: 375,
    borderRadius: 8,
    backgroundColor: COLORS.platform.redLight,
    borderColor: COLORS.platform.redMain,
    borderWidth: 1,
    borderStyle: "solid",
  },
  success: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    height: 64,
    maxHeight: 64,
    width: 375,
    borderRadius: 8,
    backgroundColor: COLORS.platform.greenLight,
    borderColor: COLORS.platform.greenMain,
    borderWidth: 1,
    borderStyle: "solid",
  },
  warning: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
    marginLeft: 10,
    marginRight: 10,
    height: 64,
    maxHeight: 64,
    width: 375,
    borderRadius: 8,
    backgroundColor: COLORS.platform.yellowLight,
    borderColor: COLORS.platform.yellowDark,
    borderWidth: 1,
    borderStyle: "solid",
  },
});
